[package]
name = "kilo-edit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23.2"
errno = "0.2.8"

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
